name: continuous integration

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/ContinuousIntegration.yml'
      - 'source/DefaultSerialization/**'

jobs:
  continuous_integration:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        source-url: https://nuget.pkg.github.com/Doraku/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Run tests net462
      run: dotnet test source\DefaultSerialization.Test\DefaultSerialization.Test.csproj -c Release -f net462
      env:
        TEST: true

    - name: Run tests net48
      run: dotnet test source\DefaultSerialization.Test\DefaultSerialization.Test.csproj -c Release -f net48
      env:
        TEST: true

    - name: Run tests net8.0
      run: dotnet test source\DefaultSerialization.Test\DefaultSerialization.Test.csproj -c Release -f net8.0
      env:
        TEST: true
      
    - name: Decrypte snk file
      env:
        SNK_KEY: ${{ secrets.SNK_KEY }}
      run: gpg --quiet --batch --yes --decrypt --passphrase="$env:SNK_KEY" --output ds.snk ds.snk.gpg

    - name: Create package
      run: dotnet pack source\DefaultSerialization\DefaultSerialization.csproj -c Release -o build /p:CI_VERSION=true

    - name: Publish package
      run: nuget push build\*.nupkg
